training:
  batch_size: 1_000
  epochs: 100
  save_every: 0
  restore: False

opts:
  log: True
  folder: ~/experiments/infection
  session: _auto_
  cpus: _auto_
  seed: _auto_
  device: _auto_

optimizer:
  _class_: torch.optim.Adam
