model:
  _class_: count_nodes.networks.FullGN
  in_edge_features_shape: 2
  in_node_features_shape: 4
  in_global_features_shape: 2
  out_edge_features_shape: 2
  out_node_features_shape: 1
  out_global_features_shape: 1
